### ISSUE TITLE
Can we calculate test coverage on Android?

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-runtime-android#12]
If so, how do we set it up for our projects?

**Comment by seanoshea** [comment]
Can definitely integrate with something like codecov for Android projects. https://github.com/material-motion/material-motion-runtime-android/pull/19 is one example of hooking the build up to travis and codecov. Externally, https://github.com/seanoshea/BluePlaquesLondon-Android is one example of how this can be implemented with circleci.

**Comment by seanoshea** [comment]
Given https://codecov.io/gh/material-motion/material-motion-runtime-android, should we close this out now?

**Comment by jverkoey** [comment]
Yeah this looks answered!
