### ISSUE TITLE
Allow local disk maven repository dependency

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-runtime-android#13]
Currently, a client's debug builds need to depend on `git@github.com:material-motion/material-motion-runtime-android:develop`.

**Comment by jverkoey** [comment]
For context: this will allow a dev to make changes to the runtime and reference them from the transitions library without having to publish those changes to an external repo.

**Comment by pingpongboss** [comment]
Extra context: http://codereview.cc/D1197

**Comment by pingpongboss** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1237

**Comment by pingpongboss** [comment]
💻 I'm working on a diff at http://codereview.cc/D1237

**Comment by pingpongboss** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1237
