### ISSUE TITLE
Allow local disk maven repository dependency on a per-project basis

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-runtime-android#17]
Per-project basis means that within a library, there are multiple projects. Usually this means that there is a `library` and `sample` project.

It's unclear if there are any use cases for different projects to want to use different versions. 

Similar to https://github.com/material-motion/material-motion-runtime-android/issues/13 but allow scoping to a specific project within the library.

**Comment by jverkoey** [comment]
Moved to https://github.com/material-motion/material-motion-team/issues/154.
