### ISSUE TITLE
Remove Performer param from DelegatedPerformanceCallback methods

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-runtime-android#18]
Pros:
Performer will not have to pass `this` when calling DelegatedPerformanceCallback https://github.com/material-motion/material-motion-runtime-android/blob/develop/sample/src/main/java/com/google/android/material/motion/runtime/sample/MainActivity.java#L122

Cons:
Currently the DelegatedPerformanceCallback is only instantiated once. The proposal will instantiate a new callback for every Performer. https://github.com/material-motion/material-motion-runtime-android/blob/develop/library/src/main/java/com/google/android/material/motion/runtime/TargetScope.java#L143

**Comment by jverkoey** [comment]
I can't tell whether this issue is resolved. @pingpongboss can you update?

**Comment by pingpongboss** [comment]
DelegatedPerformance is now ContinuousPerformance. API no longer requires the Performer to pass in `this`.
