### ISSUE TITLE
Add a unit test for a composable plan

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-runtime-android#21]
Blocked by #20.

**Comment by jverkoey** [comment]
Simple test idea:

RootPlan composes to LeafPlan and LeafPlan changes some state on the target. The test would then assert that this state change occurred.

**Comment by seanoshea** [comment]
Should we close this out as https://github.com/material-motion/material-motion-runtime-android/pull/28 has been merged in?

**Comment by pingpongboss** [comment]
Yup. Thanks!
