### ISSUE TITLE
How do we integrate robolectric with gradle?

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-runtime-android#22]

**Comment by miguelandres** [comment]
I have some robolectric tests in @material-foundation

It's working fine.

This is what my build.gradle's deps look like

dependencies {
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support:design:24.1.1'
    compile 'com.android.support:recyclerview-v7:24.1.1'
    compile 'com.android.support:support-annotations:24.1.1'
    compile project(':core')
    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:2.0.87-beta'
    **testCompile 'org.robolectric:robolectric:3.1.1'**
}

**Comment by jverkoey** [comment]
Moved to https://github.com/material-motion/material-motion-team/issues/156.
