### ISSUE TITLE
Create test for DelegatedPerformance.

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-runtime-android#26]
This test depends on animate(), which may not work well with testing on the emulator.

See https://github.com/material-motion/material-motion-runtime-android/pull/25 for context

**Comment by seanoshea** [comment]
Assuming that this should be closed out with https://github.com/material-motion/material-motion-runtime-android/pull/27 merged into develop? Or, if there are other sections of `DelgatedPerformance` that you would like to see tested?
