### ISSUE TITLE
Integrate unit tests with arc

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-runtime-android#31]
Right now all commits pushed to github run through circleci https://travis-ci.org/material-motion/material-motion-runtime-android/builds

You can also manually invoke the tests with `./gradlew :library:connectedAndroidTest`

We should configure arc to automatically run unit tests upon export or land.

**Comment by jverkoey** [comment]
Moved to https://github.com/material-motion/material-motion-team/issues/143.
