### ISSUE TITLE
Include documentation explaining what tools are required to run the examples

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-runtime-android#32]
Including links to the expected tools will be helpful for someone coming to this library as a new android developer.

See https://github.com/material-motion/material-motion-runtime-objc#installation-with-cocoapods for an example of explaining what a tool is and how to install it.

**Comment by pingpongboss** [comment]
I think this has been done for a long time. See https://github.com/material-motion/material-motion-runtime-android/blob/develop/README.md#installation
