### ISSUE TITLE
Hook up unit tests to Travis CI

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-runtime-android#4]
Blocked on https://github.com/material-motion/material-motion-runtime-android/issues/1.

**Comment by seanoshea** [comment]
Taking a look at this issue at https://github.com/seanoshea/material-motion-runtime-android/tree/issues/4-travis-unit-tests. Seems like I can get it to pass sometimes (https://travis-ci.org/seanoshea/material-motion-runtime-android/builds/149366702) and other times it fails (https://travis-ci.org/seanoshea/material-motion-runtime-android/builds/149543452) with the exact same codebase.

FWIW, I've had issues in the past with travis-ci and Android testing. Moved over to circleci with https://github.com/seanoshea/BluePlaquesLondon-Android/issues/135 on a personal project and it seems like its pretty solid so far. I've never had any false positive failures when building the app.

I wonder if we could get any help from the folks at travis-ci to understand a little more about why we are having intermittent issues connecting to the emulator? Will keep hacking away at this in the meantime to see if I can get a more consistent build.

**Comment by pingpongboss** [comment]
Hi Sean, thanks for jumping on this! Personally, I do not have any experience with travisci, so I don't think I can help with much. But I did notice that your "I can get it to pass sometimes" example (https://travis-ci.org/seanoshea/material-motion-runtime-android/builds/149526777) shows the same failure.

If you ever want to chat, our team is on Discord https://discord.gg/ZJyGXza and you are welcomed to join us.

**Comment by seanoshea** [comment]
Oooops. Wrong link in that previous comment. Managed to get it to pass in https://travis-ci.org/seanoshea/material-motion-runtime-android/builds/149366702, but can't get this working consistently. There's nothing worse than an inconsistent build, so will continue hacking away on this for a bit and see if I can come to some kind of workable solution.

**Comment by pingpongboss** [comment]
Not sure if this helps, but both http://stackoverflow.com/a/33571279/450396 and http://stackoverflow.com/a/28949723/450396 suggest that updating to gradle 2.0.0-beta3 may help.

**Comment by seanoshea** [comment]
Closing this as https://github.com/material-motion/material-motion-runtime-android/pull/19 has been merged in.
